#-----------------------------------------------------------------------------#
#   app.yaml                                                                  #
#                                                                             #
#   Copyright (c) 2010-2012, Code A La Mode, original authors.                #
#                                                                             #
#       This file is part of Social Butterfly.                                #
#                                                                             #
#       Social Butterfly is free software; you can redistribute it and/or     #
#       modify it under the terms of the GNU General Public License as        #
#       published by the Free Software Foundation, either version 3 of the    #
#       License, or (at your option) any later version.                       #
#                                                                             #
#       Social Butterfly is distributed in the hope that it will be useful,   #
#       but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#       GNU General Public License for more details.                          #
#                                                                             #
#       You should have received a copy of the GNU General Public License     #
#       along with Social Butterfly.  If not, see:                            #
#           <http://www.gnu.org/licenses/>.                                   #
#-----------------------------------------------------------------------------#


application: social-butterfly
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on
- deferred: on


handlers:

- url: /humans.txt
  static_files: assets/humans.txt
  upload: assets/humans.txt

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /sitemap.xml
  static_files: assets/sitemap.xml
  upload: assets/sitemap.xml

- url: /notifications
  static_files: assets/notifications.html
  upload: assets/notifications.html
  expiration: "7d"

- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico
  expiration: "7d"

- url: /assets/sticky
  static_dir: assets/sticky
  expiration: "7d"

- url: /assets/images
  static_dir: assets/images
  expiration: "7d"

- url: /assets
  static_dir: assets

- url: /_ah/mail/.+
  script: main.py
  login: admin

- url: /.*
  script: main.py


inbound_services:
- channel_presence
- xmpp_message
- xmpp_presence
- xmpp_subscribe
- mail


skip_files:

# Default stuff:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*

# Social Butterfly specific stuff:
- ^(.*/)?.*\.swp$
- ^(.*/)?IGNORE\.txt
